### ISSUE TITLE
No improvement compared to scipy.optimize.nnls

### ISSUE THREAD

**Issue by MNagtegaal** [jvendrow/fnnls#4]
Thanks for the initiative to translate this paper to python, I tried to use it and ran into the following problem.

## Description
I installed fnnls with pip and downloaded the test/nnls_comparison.py script. 
The resulting plot I got (with a number of 10 iterations) was:

![image](https://user-images.githubusercontent.com/50950962/147208501-ce21b0c7-3418-4df9-aa42-7cb315620c70.png)

Not showing a clear improvement compared to NNLS, actually the opposite. 

## Environment
I ran this with python 3.7.6, scipy 1.5.0, numpy 1.19.1 under a Windows installation. 

I could not find which versions were used for initial testing.

**Comment by jvendrow** [comment]
Hi Martijn! This is very strange indeed. I originally performed testing with slightly earlier version of `NumPy` and `SciPy`, however I just installed the versions you were using and still get approximately the same plot showing significant improvement from `fnnls`. 

I am running my code on a 2018 Macbook Pro, I just ran the testing script on another Macbook and got similar results to mine, so the problem might be with the difference between devices. I can try running my code on a Windows computer when I get access to one and see if that is what makes the difference, some of the `NumPy` operations used might be slower on your computer.

**Comment by MNagtegaal** [comment]
Hi Joshua,
Yes I can imagine that there will be some differences when using a different system, but I did not expect them to be this large.
The scipy code mainly relies on a fortran implementation, which is probably less dependent of underlying installations and or BLAS, LAPACK availability…
On a side not; did you ever try to use numba or other just in time compiler options to achieve an extra speedup?
Best,
Martijn

Van: Joshua Vendrow ***@***.***>
Verzonden: donderdag 23 december 2021 09:39
Aan: jvendrow/fnnls ***@***.***>
CC: Martijn Nagtegaal ***@***.***>; Author ***@***.***>
Onderwerp: Re: [jvendrow/fnnls] No improvement compared to scipy.optimize.nnls (Issue #4)


Hi Martijn! This is very strange indeed. I originally performed testing with slightly earlier version of NumPy and SciPy, however I just installed the versions you were using and still get approximately the same plot showing significant improvement from fnnls.

I am running my code on a 2018 Macbook Pro, I just ran the testing script on another Macbook and got similar results to mine, so the problem might be with the difference between devices. I can try running my code on a Windows computer when I get access to one and see if that is what makes the difference, some of the NumPy operations used might be slower on your computer.

—
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_jvendrow_fnnls_issues_4-23issuecomment-2D1000135403&d=DwMCaQ&c=XYzUhXBD2cD-CornpT4QE19xOJBbRy-TBPLK0X9U2o8&r=vQw2W41_MxqchW9cX9OYjprQL6qmd_PslIQ1GFaCMDA&m=hNeZ0cz436dkhkF6RQHcUImlrh3ufnFOJt5QR98plaY&s=EbszipGZ7VL_mHatKn2Yc7sEV58gcuxFRb4GlwoPDbY&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AMEXGMQR46XJCJRPTOK4FFTUSLN3FANCNFSM5KUHHZNA&d=DwMCaQ&c=XYzUhXBD2cD-CornpT4QE19xOJBbRy-TBPLK0X9U2o8&r=vQw2W41_MxqchW9cX9OYjprQL6qmd_PslIQ1GFaCMDA&m=hNeZ0cz436dkhkF6RQHcUImlrh3ufnFOJt5QR98plaY&s=05nSLrvCVrJQW4wwMoCa97T84soAQFckgXW9OFwYqtg&e=>.
Triage notifications on the go with GitHub Mobile for iOS<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=XYzUhXBD2cD-CornpT4QE19xOJBbRy-TBPLK0X9U2o8&r=vQw2W41_MxqchW9cX9OYjprQL6qmd_PslIQ1GFaCMDA&m=hNeZ0cz436dkhkF6RQHcUImlrh3ufnFOJt5QR98plaY&s=TSEyNJ8wjXVK2yUaRWhuWsNW9ImBdAlBO0sGSnqkAks&e=> or Android<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=XYzUhXBD2cD-CornpT4QE19xOJBbRy-TBPLK0X9U2o8&r=vQw2W41_MxqchW9cX9OYjprQL6qmd_PslIQ1GFaCMDA&m=hNeZ0cz436dkhkF6RQHcUImlrh3ufnFOJt5QR98plaY&s=vOjy_WwKoVenk3fjO5ns8Js40SazP4qSAmUr2d1sWsQ&e=>.

**Comment by jvendrow** [comment]
I haven't looked into anything like Numba but it is definitely something I'll try now that you suggest it, especially since on the website they advertise speeds "approaching C and Fortran" which seems to be an underlying difference between the `SciPy` and `fnnls` code.

Something interesting but following expectations is that between our runs the `SciPy` code has around the same runtime while the `fnnls` runtime changes, which is consistent with `SciPy` being less dependent on underlying installs.
